# Generated by Django 3.0.3 on 2020-02-27 16:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='ok'),
            preserve_default=False,
        ),
    ]
